SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [rpt].[vw_SchoolYear]
AS

SELECT DISTINCT SchoolYear
FROM dbo.Season_SchoolYear
WHERE LEFT(SchoolYear,2) <= RIGHT(CAST(YEAR(GETDATE()) AS NVARCHAR(4)),2)
GO
