SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [segmentation].[vw__CLA_Pac_Attendance]
AS
( 

SELECT 
SSBID.SSB_CRMSYSTEM_CONTACT_ID
,tkSeatSeat.SEASON AS SDT_SEASON
, Season.NAME AS SDT_SEASON_NAME
, tkSeatSeat.EVENT AS SDT_EVENT
, Event.NAME AS SDT_EVENT_NAME
, tkSeatSeat.LEVEL AS SDT_LEVEL
, tkSeatSeat.SECTION AS SDT_SECTION
, tkSeatSeat.ROW  AS SDT_ROW
, tkSeatSeat.SEAT AS SDT_SEAT
, tkSeatSeat.STAT AS SDT_STAT
, SStat.NAME AS SDT_STAT_NAME
, tkSeatSeat.ITEM AS SDT_ITEM
, Item.NAME AS SDT_ITEM_NAME
, tkSeatSeat.I_PT AS SDT_PRICE_TYPE
, PRType.NAME AS SDT_PRICE_TYPE_NAME
, PRType.CLASS AS SDT_PRICE_TYPE_CLASS
, tkSeatSeat.PL AS SDT_PL
, PRLev.PL_NAME AS SDT_PL_NAME
, tkSeatSeat.PREV_STATUS AS SDT_PREV_STATUS
, SStat2.NAME AS SDT_PREV_STATUS_NAME
, tkSeatSeat.AISLE AS SDT_AISLE
, ISNULL(CONVERT(DATETIME, ODet.I_DATE, 120), '') AS SDT_ORDER_DATE
, ODet.I_PRICE AS SDT_ORDER_PRICE
, bc.SCAN_DATE		AS SDT_SCAN_DATE
, bc.SCAN_TIME		AS SDT_SCAN_TIME
, bc.SCAN_LOC		AS SDT_SCAN_LOC
, bc.SCAN_CLUSTER	AS SDT_SCAN_CLUSTER
, bc.SCAN_GATE		AS SDT_SCAN_GATE
, bc.SCAN_RESPONSE	AS SDT_SCAN_RESPONSE
, bc.REDEEMED		AS SDT_REDEEMED
, bc.ATTENDED		AS SDT_ATTENDED
FROM dbo.TK_SEAT_SEAT tkSeatSeat WITH (NOLOCK)
JOIN dbo.TK_SEASON Season WITH (NOLOCK) ON Season.SEASON = tkSeatSeat.SEASON
JOIN dbo.TK_EVENT Event WITH (NOLOCK) ON Event.SEASON = tkSeatSeat.SEASON AND Event.EVENT = tkSeatSeat.EVENT
LEFT JOIN dbo.TK_SSTAT SStat WITH (NOLOCK) ON SStat.SEASON = tkSeatSeat.SEASON AND SStat.SSTAT = tkSeatSeat.STAT
LEFT JOIN dbo.TK_SSTAT SStat2 WITH (NOLOCK) ON SStat2.SEASON = tkSeatSeat.SEASON AND SStat2.SSTAT = tkSeatSeat.PREV_STATUS
LEFT JOIN dbo.TK_ITEM Item WITH (NOLOCK) ON Item.SEASON = tkSeatSeat.SEASON AND Item.ITEM = tkSeatSeat.ITEM
LEFT JOIN dbo.TK_PRTYPE PRType WITH (NOLOCK) ON PRType.SEASON = tkSeatSeat.SEASON AND PRType.PRTYPE = tkSeatSeat.I_PT
LEFT JOIN dbo.TK_PTABLE_PRLEV PRLev WITH (NOLOCK) ON PRLev.SEASON = tkSeatSeat.SEASON AND PRLev.PTABLE = tkSeatSeat.ITEM AND PRLev.PL = tkSeatSeat.I_PL
LEFT JOIN dbo.TK_ODET ODet WITH (NOLOCK) ON ODet.SEASON = tkSeatSeat.SEASON AND ODet.ZID = tkSeatSeat.DKEY
LEFT JOIN dbo.TK_CUSTOMER Customer WITH (NOLOCK) ON Customer.CUSTOMER = tkSeatSeat.CUSTOMER
LEFT JOIN dbo.TK_CTYPE CType WITH (NOLOCK) ON CType.TYPE = Customer.TYPE
LEFT JOIN dbo.dimcustomerssbid SSBID WITH (NOLOCK) ON SSBID.SSID = tkseatseat.CUSTOMER AND SSBID.SourceSystem = 'Pac_CLA'
LEFT JOIN dbo.TK_BC bc WITH (NOLOCK) ON bc.BC_ID = tkSeatSeat.BARCODE AND bc.SEASON = tkSeatSeat.SEASON
WHERE tkSeatSeat.SEASON LIKE 'CC%'
	AND tkSeatSeat.Customer IS NOT NULL
	AND tkSeatSeat.SEASON IN ('CC15', 'CC16')
	AND ssbid.SSB_CRMSYSTEM_CONTACT_ID IS NOT NULL
)












GO
