CREATE TABLE [dbo].[HOB_TicketSalesSummary]
(
[SeasonName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VisitorQty] [int] NULL,
[VisitorRevenue] [decimal] (18, 6) NULL,
[WalkUpQty] [int] NULL,
[WalkUpRevenue] [decimal] (18, 6) NULL,
[STHQty] [int] NULL,
[STHRevenue] [decimal] (18, 6) NULL,
[MiniPlanQty] [int] NULL,
[MiniPlanRevenue] [decimal] (18, 6) NULL,
[PartialPlanQty] [int] NULL,
[PartialPlanRevenue] [decimal] (18, 6) NULL,
[FlexPlanQty] [int] NULL,
[FlexPlanRevenue] [decimal] (18, 6) NULL,
[GroupQty] [int] NULL,
[GroupRevenue] [decimal] (18, 6) NULL,
[GroupGoal] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GroupGoalPct] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StudentQty] [int] NULL,
[StudentRevenue] [decimal] (18, 6) NULL,
[StudentGoal] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StudentGoalPct] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SingleGameQty] [int] NULL,
[SingleGameRevenue] [decimal] (18, 6) NULL,
[ArchticsSingleGameQty] [int] NULL,
[ArchticsSingleGameRevenue] [decimal] (18, 6) NULL,
[MobileQty] [int] NULL,
[MobileRevenue] [decimal] (18, 6) NULL,
[TotalSold] [int] NULL,
[TotalScanned] [int] NULL,
[AvailableQty] [int] NULL,
[PctAttended] [decimal] (18, 6) NULL,
[TicketExchangeQty] [int] NULL,
[TicketExchangeRevenue] [decimal] (18, 6) NULL,
[TotalSingleGameSales] [int] NULL,
[TotalSingleGameSalesRevenue] [decimal] (18, 6) NULL,
[TotalRevenue] [decimal] (18, 2) NULL,
[CalendarDate] [date] NULL,
[DimEventHeaderID] [int] NULL
)
GO
