CREATE TABLE [segmentation].[SegmentationFlatDatab94a8b56-2adb-46c5-bb0c-1fd4fd99f93e]
(
[id] [uniqueidentifier] NOT NULL,
[DocumentType] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SessionId] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Environment] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TenantId] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[_rn] [bigint] NULL,
[SSB_CRMSYSTEM_CONTACT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AgeInTwoYearIncrements_InputIndividual] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusinessOwner] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Collectibles_SportsMemorabilia] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiscretionaryIncomeIndex] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwellingType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Education_InputIndividual] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females_18to24] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females_25to34] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females_35to44] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females_45to54] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females_55to64] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females_65to74] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Females_75plus] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender_InputIndividual] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HomeMarketValue] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HomeOwnerorRenter] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HomePropertyType_Detail] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HomeSquareFootage_Actual] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HomeYearBuilt_Actual] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Income_EstimatedHousehold] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Investing_Active] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LengthofResidence] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MailOrder_Buyer] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MailOrder_Donor] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MailOrder_Responder] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males_18to24] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males_25to34] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males_35to44] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males_45to54] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males_55to64] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males_65to74] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Males_75plus] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaritalStatusinHousehold] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MotorcycleOwner] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NetWorthGold] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccupationDetail_InputIndividual] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Occupation_InputIndividual] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnlinePurchasingIndicator] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonicxClusterCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonicxCluster] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonicxDigitalClusterCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonicxDigitalCluster] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PremiumCardHolder] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PresenceofChildren] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RaceCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RetailActivity_DateofLast] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RetailPurchases_MostFrequentCategory] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RVOwner] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpectatorSports_AutoMotorcycleRacing] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpectatorSports_Baseball] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpectatorSports_Basketball] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpectatorSports_Football] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpectatorSports_Hockey] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpectatorSports_Soccer] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpectatorSports_Tennis] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sports_GolfMOBs] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SportsAndLeisure_SC] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sports_MOBs] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StandardRetail_CatalogShowroomRetailBuyers] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StandardRetail_HighVolumeLowEndDepartmentStoreBuyers] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StandardRetail_MainStreetRetail] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StandardRetail_MembershipWarehouse] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StandardRetail_StandardRetail] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StandardSpecialty_ComputerElectronicsBuyers] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StandardSpecialty_FurnitureBuyers] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StandardSpecialty_HomeImprovement] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StandardSpecialty_HomeOfficeSupplyPurchases] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StandardSpecialty_Specialty] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StandardSpecialty_SpecialtyApparel] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StandardSpecialty_SportingGoods] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TravelandEntertainmentCardHolder] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Travel_MOBs] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TruckOwner] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpscaleCardHolder] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpscaleRetail_HighEndRetailBuyersUpscaleRetail] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpscaleSpecialty_TravelPersonalServices] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle_DominantLifestyleIndicator] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle_KnownOwnedNumber] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle_NewCarBuyer] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle_NewUsedIndicator_1stVehicle] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle_NewUsedIndicator_2ndVehicle] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WorkingWoman] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TurnkeyStandardBundleDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RN] [bigint] NULL
)
GO
ALTER TABLE [segmentation].[SegmentationFlatDatab94a8b56-2adb-46c5-bb0c-1fd4fd99f93e] ADD CONSTRAINT [pk_SegmentationFlatDatab94a8b56-2adb-46c5-bb0c-1fd4fd99f93e] PRIMARY KEY NONCLUSTERED  ([id])
GO
CREATE CLUSTERED INDEX [cix_SegmentationFlatDatab94a8b56-2adb-46c5-bb0c-1fd4fd99f93e] ON [segmentation].[SegmentationFlatDatab94a8b56-2adb-46c5-bb0c-1fd4fd99f93e] ([_rn])
GO
