CREATE TABLE [stg].[rpt_TicketSalesSummary]
(
[SeasonName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventDate] [date] NULL,
[VisitorQty] [int] NULL,
[VisitorRevenue] [decimal] (15, 2) NULL,
[WalkUpQty] [int] NULL,
[WalkUpRevenue] [decimal] (15, 2) NULL,
[STHQty] [int] NULL,
[STHRevenue] [decimal] (15, 2) NULL,
[MiniPlanQty] [int] NULL,
[MiniPlanRevenue] [decimal] (15, 2) NULL,
[PartialPlanQty] [int] NULL,
[PartialPlanRevenue] [decimal] (15, 2) NULL,
[FlexPlanQty] [int] NULL,
[FlexPlanRevenue] [decimal] (15, 2) NULL,
[GroupQty] [int] NULL,
[GroupRevenue] [decimal] (15, 2) NULL,
[GroupGoal] [int] NULL,
[GroupGoalPct] [decimal] (15, 2) NULL,
[StudentQty] [int] NULL,
[StudentRevenue] [decimal] (15, 2) NULL,
[StudentGoal] [int] NULL,
[StudentGoalPct] [decimal] (15, 2) NULL,
[SingleGameQty] [int] NULL,
[SingleGameRevenue] [decimal] (15, 2) NULL,
[TicketExchangeQty] [int] NULL,
[TicketExchangeRevenue] [decimal] (15, 2) NULL,
[MiscQty] [int] NULL,
[MiscRevenue] [decimal] (15, 2) NULL,
[AvailableQty] [int] NULL,
[AvailableRevenue] [decimal] (15, 2) NULL,
[TotalSold] [int] NULL,
[TotalScanned] [int] NULL,
[PctAttended] [decimal] (15, 2) NULL,
[MobileQty] [int] NULL,
[MobileRevenue] [int] NULL
)
GO
